openapi: 3.0.1
info:
  title: Credentials
  description: |-
        This api is used for digital certificate assertion.
        - [Testcases](https://app.getpostman.com/run-collection/4d683e7b17b98026c267)
  version: "1.0"
servers:
- url: https://staging.open-sunbird.org/api
paths:
  allOf:
    - $ref: /apis/certificate/certificate.yaml
    - $ref: /apis/certificateregistry/certificateregistryapi.yaml