openapi: 3.0.1
info:
  title: Course Progress APIs
  description: |-
    The Course Progress API resource is used to publish and update the status of the course as consumed by a user. The operations include the basic course status and the updated status.

    The URL for Course Progress API is /course/v1/user/content/state.
    - Postman collection for testcases - [TestCases](https://www.getpostman.com/collections/166e85c10db9c1ef0783)
    - For different request, response examples please refer doc - [Postman Doc](https://documenter.getpostman.com/view/7127399/TVmHEKmj)
    - [TermsOfService](https://github.com/project-sunbird/sunbird-commons/blob/master/LICENSE)
    - Contact - [info@sunbird.org](info@sunbird.org)
  contact: {}
  version: '1.0'
servers:
  - url: 'https://staging.sunbirded.org/api/course/v1/content/state'
    variables: {}
paths:
  /read:
    post:
      tags:
        - Course Progress API(s)
      summary: Read Content State
      description: |-
        This API is used for reading the current progress of the course (content) consumed by a user. For example, the user can view and check the progress of a specific course or course(s) consumed.

        - The endpoint for **Read Course State** is `/read`

        - The fields marked with an asterisk (*) are mandatory.
        They cannot be null or empty.
      operationId: ReadContentState
      parameters:
        - name: Content-Type
          in: header
          description: "The Content Type entity is the media type of the resource. Possible\
            \ media types are:- \n  - Application/json\n  - Multipart/form-data\n  -\
            \ Application/x-www-form-urlencoded"
          required: true
          schema:
            type: string
            example: 'application/json'
        - name: Authorization
          in: header
          description: 'To make use of the API, you require authorization. Raise a request
          to the administrator for the use of the API. You will receive the authorization
          key. Specify the key received, here.'
          required: true
          style: simple
          schema:
            type: string
            example: '{{api-key}}'
        - name: x-authenticated-user-token
          in: header
          description: 'The registered user token/key to authenticate user and execute
          the API.'
          required: true
          style: simple
          schema:
            type: string
            example: '{{authToken}}'
      requestBody:
        description: 'Represents the body and formdata parameters of the course
          progress state API'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReadContentStateRequest'
            example:
              request:
                userId: '{{user-id}}'
                courseId: '{{course-id}}'
                contentIds:
                  - '{{content-id}}'
                batchId: '{{batch-id}}'
        required: true
      responses:
        '200':
          description: 'SUCCESS. The "Read Course States" operation was successful!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadContentState-Contentnotconsumed'
              example:
                id: api.content.state.read
                ver: v1
                ts: '2020-11-24 07:34:28:089+0000'
                params:
                  resmsgid: null
                  msgid: f00d1bf0-4014-40bb-b055-4972e598977a
                  err: null
                  status: success
                  errmsg: null
                responseCode: OK
                result:
                  contentList: []
      deprecated: false
      security: []
  /update:
    patch:
      tags:
        - Course Progress API(s)
      summary: Update Content State
      description: |-
        This API is used to update the Course(content) state as consumed by a user. For example, when the user resumes a course or courses after the point at which it was stopped, the status of the course is updated.

        The endpoint for **Update Course State** is `/update`

        The fields marked with an asterisk (*) are mandatory. They cannot be null or empty.
      operationId: UpdateContentState
      parameters:
        - name: Content-Type
          in: header
          description: "The Content Type entity is the media type of the resource. Possible\
            \ media types can be:- \n  - Application/json\n  - Multipart/form-data\n\
            \  - Application/x-www-form-urlencoded"
          required: true
          schema:
            type: string
            example: 'application/json'
        - name: Authorization
          in: header
          description: 'To make use of the API, you require authorization. Raise a request
          to the administrator for the use of the API. You will receive the authorization
          key. Specify the key received, here.'
          required: true
          style: simple
          schema:
            type: string
            example: '{{api-key}}'
        - name: x-authenticated-user-token
          in: header
          description: 'The registered user token/key to authenticate user and execute
          the API.'
          required: true
          style: simple
          schema:
            type: string
            example: '{{authToken}}'
      requestBody:
        description: 'Represents the body and formdata parameters of the course progress
          state API'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateContentStateRequest'
            example:
              request:
                userId: '{{user-id}}'
                contents:
                  - contentId: '{{content-id}}'
                    batchId: '{{batch-id}}'
                    status: 2
                    courseId: '{{course-id}}'
                    lastAccessTime: '2020-11-23 12:58:35:179+0000'
        required: true
      responses:
        '200':
          description: 'SUCCESS. The "Update Course State" operation was successful!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateContentState-200OK-Success'
              example:
                id: api.content.state.update
                ver: v1
                ts: '2020-11-27 14:07:27:025+0000'
                params:
                  resmsgid: null
                  msgid: 74aa2cb5-0580-4183-adff-c6e69204f1ee
                  err: null
                  status: success
                  errmsg: null
                responseCode: OK
                result:
                  do_11259843042561228816: SUCCESS
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateContentState-500InternalServerError'
              example:
                id: api.content.state.update
                ver: v1
                ts: '2020-11-24 07:37:21:727+0000'
                params:
                  resmsgid: null
                  msgid: null
                  err: INTERNAL_ERROR
                  status: SERVER_ERROR
                  errmsg: 'Process failed,please try again later.'
                responseCode: SERVER_ERROR
                result: {}
      deprecated: false
      security: []
components:
  schemas:
    ReadContentStateRequest:
      title: ReadContentStateRequest
      required:
        - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/Request'
      example:
        request:
          userId: '{{user-id}}'
          courseId: '{{course-id}}'
          contentIds:
            - '{{content-id}}'
          batchId: '{{batch-id}}'
    Request:
      title: Request
      required:
        - userId
        - courseId
        - contentIds
        - batchId
      type: object
      properties:
        userId:
          type: string
        courseId:
          type: string
        contentIds:
          type: array
          items:
            type: string
          description: ''
        batchId:
          type: string
      example:
        userId: '{{user-id}}'
        courseId: '{{course-id}}'
        contentIds:
          - '{{content-id}}'
        batchId: '{{batch-id}}'
    ReadContentState-Contentnotconsumed:
      title: ReadContentState-Contentnotconsumed
      required:
        - id
        - ver
        - ts
        - params
        - responseCode
        - result
      type: object
      properties:
        id:
          type: string
        ver:
          type: string
        ts:
          type: string
        params:
          $ref: '#/components/schemas/Params'
        responseCode:
          type: string
        result:
          $ref: '#/components/schemas/Result'
      example:
        id: api.content.state.read
        ver: v1
        ts: '2020-11-24 07:34:28:089+0000'
        params:
          resmsgid: null
          msgid: f00d1bf0-4014-40bb-b055-4972e598977a
          err: null
          status: success
          errmsg: null
        responseCode: OK
        result:
          contentList: []
    Params:
      title: Params
      required:
        - resmsgid
        - msgid
        - err
        - status
        - errmsg
      type: object
      properties:
        resmsgid:
          type: string
          nullable: true
        msgid:
          type: string
        err:
          type: string
          nullable: true
        status:
          type: string
        errmsg:
          type: string
          nullable: true
      example:
        resmsgid: null
        msgid: f00d1bf0-4014-40bb-b055-4972e598977a
        err: null
        status: success
        errmsg: null
    Result:
      title: Result
      required:
        - contentList
      type: object
      properties:
        contentList:
          type: array
          items:
            type: string
          description: ''
      example:
        contentList: []
    UpdateContentStateRequest:
      title: UpdateContentStateRequest
      required:
        - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/Request1'
      example:
        request:
          userId: '{{user-id}}'
          contents:
            - contentId: '{{content-id}}'
              batchId: '{{batch-id}}'
              status: 2
              courseId: '{{course-id}}'
              lastAccessTime: '2020-11-23 12:58:35:179+0000'
    Request1:
      title: Request1
      required:
        - userId
        - contents
      type: object
      properties:
        userId:
          type: string
        contents:
          type: array
          items:
            $ref: '#/components/schemas/Content'
          description: ''
      example:
        userId: '{{user-id}}'
        contents:
          - contentId: '{{content-id}}'
            batchId: '{{batch-id}}'
            status: 2
            courseId: '{{course-id}}'
            lastAccessTime: '2020-11-23 12:58:35:179+0000'
    Content:
      title: Content
      required:
        - contentId
        - batchId
        - status
        - courseId
        - lastAccessTime
      type: object
      properties:
        contentId:
          type: string
        batchId:
          type: string
        status:
          type: integer
          format: int32
        courseId:
          type: string
        lastAccessTime:
          type: string
      example:
        contentId: '{{content-id}}'
        batchId: '{{batch-id}}'
        status: 2
        courseId: '{{course-id}}'
        lastAccessTime: '2020-11-23 12:58:35:179+0000'
    UpdateContentState-200OK-Success:
      title: UpdateContentState-200OK-Success
      required:
        - id
        - ver
        - ts
        - params
        - responseCode
        - result
      type: object
      properties:
        id:
          type: string
        ver:
          type: string
        ts:
          type: string
        params:
          $ref: '#/components/schemas/Params'
        responseCode:
          type: string
        result:
          $ref: '#/components/schemas/Result1'
      example:
        id: api.content.state.update
        ver: v1
        ts: '2020-11-27 14:07:27:025+0000'
        params:
          resmsgid: null
          msgid: 74aa2cb5-0580-4183-adff-c6e69204f1ee
          err: null
          status: success
          errmsg: null
        responseCode: OK
        result:
          do_11259843042561228816: SUCCESS
    Result1:
      title: Result1
      required:
        - do_11259843042561228816
      type: object
      properties:
        do_11259843042561228816:
          type: string
      example:
        do_11259843042561228816: SUCCESS
    UpdateContentState-500InternalServerError:
      title: UpdateContentState-500InternalServerError
      required:
        - id
        - ver
        - ts
        - params
        - responseCode
        - result
      type: object
      properties:
        id:
          type: string
        ver:
          type: string
        ts:
          type: string
        params:
          $ref: '#/components/schemas/Params2'
        responseCode:
          type: string
        result:
          type: object
      example:
        id: api.content.state.update
        ver: v1
        ts: '2020-11-24 07:37:21:727+0000'
        params:
          resmsgid: null
          msgid: null
          err: INTERNAL_ERROR
          status: SERVER_ERROR
          errmsg: 'Process failed,please try again later.'
        responseCode: SERVER_ERROR
        result: {}
    Params2:
      title: Params2
      required:
        - resmsgid
        - msgid
        - err
        - status
        - errmsg
      type: object
      properties:
        resmsgid:
          type: string
          nullable: true
        msgid:
          type: string
          nullable: true
        err:
          type: string
        status:
          type: string
        errmsg:
          type: string
      example:
        resmsgid: null
        msgid: null
        err: INTERNAL_ERROR
        status: SERVER_ERROR
        errmsg: 'Process failed,please try again later.'
tags:
  - name: Course Progress API(s)
    description: ''
