openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  securitySchemes:
    auth:
      type: apiKey
      name: Authorization
      in: header
    userToken:
      type: apiKey
      name: x-authenticated-user-token
      in: header
