openapi: 3.0.1
info:
  version: '1.0'
  title: Kong Credential Register API V1
  termsOfService: 'https://github.com/project-sunbird/sunbird-commons/blob/master/LICENSE'
  description: >-
    The kong credential register API V1 is used register a credential for an user or device into the kong's database. The pre-requisite is that the consumer needs to be already present in the kong's database. This API will respond back with a credentail usually called the bearer token. The bearer token will have the same permissions as the consumer. This API is generally used by the mobile app to register the mobile device. By doing so the mobile device will receive a bearer token which can used to access the API's. This API can be used for creating credentials for user's and is not restricted to mobile devices.
paths:
  /api-manager/v1/consumer/{consumer}/credential/register:
    post:
      description: |-
        This API is used to obtain a bearer token
           - Required fields cannot be left null or empty
      summary: Get a new bearer token
      tags:
        - Kong Credential Register API V1
      operationId: KongCredentialRegisterV1
      parameters:
        - in: path
          name: consumer
          required: true
          description: Append any text to the request URL
          example: mobile_device
          schema:
            type: string
      requestBody:
        required: true
        description: A unique value which helps in identifying the token
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UniqueKey'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialRegisterV1Response'
              example:
                id: "ekstep.api.am.adminutil.consumer.create"
                ver: "1.0"
                ts: 1606903294596
                params:
                  status: "successful"
                  err: null
                  errmsg: null
                  msgid: ""
                  resmsgid: "0a0d4cc2-58c0-42e0-bd98-66004517cf00"
                result:
                  key: "SunbirdUser"
                  secret: "tzppMyvMWJTA8Y5FUxoyvjCLswa47u7Pi"
                  token: "eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJTdW5iaXJkVXNlciIsImlhdCI6MTUxNjIzOTAyMn0.HUsyhT5jvusvN1f-Q6b9NOxAPy-HsEeC_icbpbDNjQY"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialRegisterV1Response'
              examples:
                Missing Request:
                  value:
                    id: "ekstep.api.am.adminutil.consumer.create"
                    ver: "1.0"
                    ts: 1606903294596
                    params:
                      status: "failed"
                      err: "BAD_REQUEST"
                      errmsg: "REQUEST IS MANDATORY"
                      msgid: null
                      resmsgid: "6208cc43-bc0a-41d4-80b3-e35f79d7af23"
                    result:
                      key: ""
                      secret: ""
                      token: ""
                Missing Key:
                  value:
                    id: "ekstep.api.am.adminutil.consumer.create"
                    ver: "1.0"
                    ts: 1606913532853
                    params:
                      status: "failed"
                      err: "BAD_REQUEST"
                      errmsg: "KEY IS MANDATORY"
                      msgid: null
                      resmsgid: "2a618770-f0e2-409d-9488-8b0ff10b4701"
                    result:
                      key: ""
                      secret: ""
                      token: ""
        '415':
          description: Unsupported media type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialRegisterV1UnsupportedMediaType'
              example:
                timestamp: 1606906723764
                status: 415
                error: "Unsupported Media Type"
                exception: "org.springframework.web.HttpMediaTypeNotSupportedException"
                message: "Unsupported Media Type"
                path: "/v1/consumer/mobile_device/credential/register"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialRegisterV1Response'
              example:
                id: "ekstep.api.am.adminutil.consumer.create"
                ver: "1.0"
                ts: 1606913643653
                params:
                  status: "failed"
                  err: "INTERNAL_ERROR"
                  errmsg: "UNABLE TO REGISTER CREDENTIAL DUE TO INTERNAL ERROR"
                  msgid: ""
                  resmsgid: "7467d7a4-bc49-479b-8590-ba81695ad491"
                result:
                  key: ""
                  secret: ""
                  token: ""
security:
  - bearerAuth: []
servers:
  - url: 'https://staging.open-sunbird.org/api/'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UniqueKey:
      description: A unique key which helps in identifying the token
      type: object
      properties:
        request:
          type: object
          properties:
           key:
              type: string
          required:
          - key
      required:
      - request
    CredentialRegisterV1Response:
      description: Kong credential register v1 response structure
      type: object
      properties:
        id:
          description: Represents the api id
          type: string
        ver:
          description: Represents the api version
          type: string
        ts:
          description: Represents the EPOCH epoch time in milliseconds
          type: integer
          format: int64
        params:
          type: object
          properties:
            status:
              description: Represents the status of the request
              type: string
              enum:
                - success
                - failed
            err:
              description: Represents the error
              type: string
              nullable: true
            errmsg:
              description: Represents the error message
              type: string
              nullable: true
            msgid:
              description: Represents the message id of the request
              type: string
              
            resmsgid:
              description: Represents the message id of the response
              type: string
        result:
          type: object
          properties:
            key:
              description: Represents the access token
              type: string
            secret:
              type: string
            token:
              type: string
    CredentialRegisterV1UnsupportedMediaType:
      description: Refresh token error response for unsupported media type
      type: object
      properties:
        timestamp:
          description: Represents the EPOCH (UTC) timestamp in milliseconds since EPOCH
          type: integer
          format: int64
        status:
          description: Represents the status of the request
          type: integer
        error:
          description: Represents the error type
          type: string
        exception:
          description: Represents the exception message
          type: string
        message:
          description: Represents the error message
          type: string
        path:
          description: Represents the API path the request
          type: string
