swagger: '2.0'
info:
  version: '1.0'
  title: OTP API(s)
  description: >-
    OTP (One time password) api enables user to generate OTP and verify generated OTP.
host: staging.open-sunbird.org
basePath:  /api/otp/v1
securityDefinitions:
  bearer:
      type: apiKey  # arbitrary name for the security scheme
      in: header # The secrity scheme parameter is in "header"
      name: Authorization # name of the header, query parameter or cookie
schemes:
  - https
consumes:
  - application/json
  - multipart/form-data
  - application/x-www-form-urlencoded
produces:
  - application/json
paths:
  /generate:
    post:
      description: >-
       This API is associated with generating otp on Sunbird platform.
          - The **_/otp/v1/generate_** endpoint executes the "generate otp" request based on parameters provided as metadata in the request body
          - Required fields cannot be left null or empty
      summary: generate otp
      tags: 
      - OTP APIs
      operationId: generateOtp
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: >-
            The body refers to the format of the request.
              - The body contains metadata about the request for generating otp.
        schema:  
            allOf:
             - $ref: 'https://raw.githubusercontent.com/project-sunbird/project-sunbird.github.io/dev/apis/definitions/envelope.yaml#/ApiRequest'
             - $ref: '#/definitions/GenerateOtprequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: >-
           The Content Type entity is the media type of the resource.
            Allowed media type:- 
              - Application/json
      - name: ts
        in: header
        required: true
        type: string
        description: 'Time Stamp at which creating user notes request was sent.'
      - name: X-msgid
        in: header
        required: true
        type: string
        description: 'This Id Uniquely identifies a request if the same API is executed multiple times.'
      - name: Authorization
        in: header
        required: true
        type: string
        description: 'All OTP api require authorization key. Specify the authorization key received from the administrator when placing the request for use of the API.'
      responses:
        '200':
          description: 'OK ! Successful operation."OTP sent to user" operation was successfully executed.'
          schema:  
            allOf:
             - $ref: 'https://raw.githubusercontent.com/project-sunbird/project-sunbird.github.io/dev/apis/definitions/envelope.yaml#/ApiResponse'
             - $ref: '#/definitions/SuccessResult'
        '400':
          description: 'BAD REQUEST. The "OTP generate" operation failed ! The possible reason for failure is that you may have missed providing input for a mandatory parameter. OR you may have provided incorrect data.'
          schema:  
            allOf:
             - $ref: 'https://raw.githubusercontent.com/project-sunbird/project-sunbird.github.io/dev/apis/definitions/envelope.yaml#/ApiResponse'
             - $ref: '#/definitions/OtpErrorResponse'
        '429':
          description: 'BAD REQUEST. The "OTP generate" operation failed ! The possible reason for failure is that you have consumer your daily or hourly limits.'
          schema:  
            allOf:
             - $ref: 'https://raw.githubusercontent.com/project-sunbird/project-sunbird.github.io/dev/apis/definitions/envelope.yaml#/ApiResponse'
             - $ref: '#/definitions/OtpErrorResponse'    
        '500':
          description: 'INTERNAL SERVER ERROR ! Looks like something went wrong! These errors are tracked automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.'
  /verify:
    post:
      description: >-
       This API is associated with verifying otp send to user on Sunbird platform.
          - The **_/otp/v1/verify_** endpoint executes the "verify otp" request based on parameters provided as metadata in the request body
          - Required fields cannot be left null or empty
      summary: verify otp
      tags: 
      - OTP APIs
      operationId: verifyOtp
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: >-
            The body refers to the format of the request.
              - The body contains metadata about the request for verifying otp.
        schema:  
            allOf:
             - $ref: 'https://raw.githubusercontent.com/project-sunbird/project-sunbird.github.io/dev/apis/definitions/envelope.yaml#/ApiRequest'
             - $ref: '#/definitions/VerifyOtprequest'
      - name: Content-Type
        in: header
        required: true
        type: string
        description: >-
           The Content Type entity is the media type of the resource.
            Allowed media type:- 
              - Application/json
      - name: ts
        in: header
        required: true
        type: string
        description: 'Time Stamp at which creating user notes request was sent.'
      - name: X-msgid
        in: header
        required: true
        type: string
        description: 'This Id Uniquely identifies a request if the same API is executed multiple times.'
      - name: Authorization
        in: header
        required: true
        type: string
        description: 'All OTP api require authorization key. Specify the authorization key received from the administrator when placing the request for use of the API.'
      responses:
        '200':
          description: 'OK ! Successful operation."OTP verified successfully" operation was successfully executed.'
          schema:  
            allOf:
             - $ref: 'https://raw.githubusercontent.com/project-sunbird/project-sunbird.github.io/dev/apis/definitions/envelope.yaml#/ApiResponse'
             - $ref: '#/definitions/SuccessResult'
        '400':
          description: 'BAD REQUEST. The "OTP verification" operation failed ! The possible reason for failure is that you may have missed providing input for a mandatory parameter. OR you may have provided incorrect data. OR your OTP has expired'
          schema:  
            allOf:
             - $ref: 'https://raw.githubusercontent.com/project-sunbird/project-sunbird.github.io/dev/apis/definitions/envelope.yaml#/ApiResponse'
             - $ref: '#/definitions/OtpErrorResponse'
        '500':
          description: 'INTERNAL SERVER ERROR ! Looks like something went wrong! These errors are tracked automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.'
definitions:
  OtpErrorResponse:
   title: 'OTP error response'
   properties: 
    result:
     type: object
    
  SuccessResult:
   title: 'Success response'
   type: object
   properties:
    resutl:
     type: object
     properties:
      response:
       type: string
       description: 'response value as success.'
  VerifyOtprequest:
    title: Request body for otp verification    
    type: object
    properties:
      request:
        $ref: '#/definitions/OtpVerifyRequest'
    required:
    - request
  OtpVerifyRequest:
    title: Request to verify otp
    type: object
    properties:
      key:
        description: 'either valid phone number or email. User will get OTP based on provided key either email or phone.'
        example: 9035004711 or manzarul07@gmail.com
        type: string
      type:
        description: 'A valid type of corresponding key, possible type values (phone or email)'
        type: string
      otp:
       description: 'OTP received on email or phone'
    required:
    - key
    - type 
    - otp
  GenerateOtprequest:
    title: Request body for generate otp    
    type: object
    properties:
      request:
        $ref: '#/definitions/OtpRequest'
    required:
    - request
  OtpRequest:
    title: Request to generate otp
    type: object
    properties:
      key:
        description: 'either valid phone number or email. User will get OTP based on provided key either email or phone.'
        example: 9035004711 or manzarul07@gmail.com
        type: string
      type:
        description: 'A valid type of corresponding key, possible type values (phone or email)'
        type: string
    required:
    - key
    - type