openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  schemas:
    Issuer:
      type: object
      properties:
        issuerId:
          type: string
          description: ID of an issuer
        image:
          type: string
          description: Image of an issuer
        createdDate:
          type: string
          format: yyyy-MM-dd HH:mm:ss:SSSZZZZ
        issuerUrl:
          type: string
          description: url of the issuer
        issuerIdUrl:
          type: string
          description: issuer url with ID
        name:
          type: string
          description: Name of the Issuer
        description:
          type: string
          description: details of the issuer
        email:
          type: string
          description: Valid email ID of the issuer
      description: this contains response for issuer object
