openapi: 3.0.1
servers:
- url: /
paths: {}
components:
  schemas:
    CreateContentrequest:
      title: Create ContentRequest
      required:
      - request
      type: object
      properties:
        request:
          $ref: '#/components/schemas/Request26'
      example:
        request:
          content:
            visibility: Default
            status: Draft
            contentType: Story
            code: test_cwp_3
            osId: org.ekstep.quiz.app
            languageCode: hi
            name: Test Content
            description: Test Content
            language:
            - Hindi
            createdFor:
            - 12297427021119488000
            createdBy: 89cf1a7e-dfd3-46c9-a428-d37e9a2bc001
            mimeType: application/vnd.ekstep.ecml-archive
    Request26:
      title: Request26
      required:
      - content
      type: object
      properties:
        content:
          $ref: '#/components/schemas/Content27'
    Content27:
      title: Content27
      required:
      - code
      - contentType
      - createdBy
      - createdFor
      - description
      - language
      - languageCode
      - mimeType
      - name
      - osId
      - status
      - visibility
      type: object
      properties:
        visibility:
          type: string
          description: ""
        status:
          type: string
          description: ""
        contentType:
          type: string
          description: ""
        code:
          type: string
          description: ""
        osId:
          type: string
          description: ""
        languageCode:
          type: string
          description: ""
        name:
          type: string
          description: ""
        description:
          type: string
          description: ""
        language:
          type: array
          description: ""
          items:
            type: string
        createdFor:
          type: array
          description: ""
          items:
            type: string
        createdBy:
          type: string
          description: ""
        mimeType:
          type: string
          description: ""
