openapi: 3.0.1
info:
  title: Roles API(s)
  description: "The Role API is used to provide a list of available roles in system.\
    \ It: \n  - supports data storage and other related operations\n  - allows you\
    \ to define your own repository inside Sunbird and use it to perform operations\
    \ on data\n  - allows you to use an object in different contexts, depending on\
    \ how it is implemented\n  - allows each object entity to have its own unique\
    \ payload request parameters\n  - Refer to the relevant documentation on the Sunbird\
    \ website to get the exact object payload parameters "
  version: "1.0"
servers:
- url: https://staging.open-sunbird.org/api
paths:
  /data/v1/role/read:
    get:
      summary: role list
      description: |-
        This API is associated with listing all roles.
           - The **_/role/read_** endpoint executes the "list roles" request based on parameters provided as metadata in the request body
           - Required fields cannot be left null or empty'
      operationId: roleList
      parameters:
      - name: Content-Type
        in: header
        description: "The Content Type entity is the media type of the resource.\n\
          \ Possible media types can be:- \n   - Application/json"
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        description: All roles APIs require authorization for use. Specify the authorization
          key received from the administrator when placing the request for use of
          the API.
        required: true
        schema:
          type: string
      - name: X-authenticated-user-token
        in: header
        description: user jwt token required
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK ! Successful operation."list object" operation was successfully
            executed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/roleRoleresponse'
        400:
          description: BAD REQUEST. The "list object" operation failed ! The possible
            reason for failure is that you may have missed providing input for a mandatory
            parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/roleContentCreateErrorResponse'
        500:
          description: INTERNAL SERVER ERROR ! Looks like something went wrong! These
            errors are tracked automatically, but if the problem persists feel free
            to contact us. In the meantime, try refreshing.
          content: {}
components:
  schemas:
    roleresponse:
      title: Response of role api
      type: object
      properties:
        result:
          type: object
          properties:
            roles:
              type: array
              items:
                $ref: '#/components/schemas/roleRoleList'
    roleRoleresponse:
      description: Response of role api
      allOf:
      - $ref: '#/components/schemas/roleresponse'
      - $ref: '#/components/schemas/roleResponseHeader'
    roleResponseHeader:
      title: ResponseHeader
      type: object
      properties:
        id:
          type: string
          description: API Identifier
        ver:
          type: string
          description: API version information
        ts:
          type: string
          description: API execution timespan
        params:
          $ref: '#/components/schemas/roleResponseParams'
        responseCode:
          type: object
          properties: {}
          description: 'API response code '
    roleResponseParams:
      title: Response Parameter
      type: object
      properties:
        resmsgid:
          type: string
          description: Response Message Id
        msgid:
          type: string
          description: Message Id
        err:
          type: string
          description: Error Code
        status:
          type: string
          description: Response Status
        errmsg:
          type: string
          description: Error Message
    roleEmptyResult:
      title: Empty Result
      type: object
      properties:
        result:
          type: object
          properties: {}
          description: Empty Result
    roleRoleList:
      title: List of roles
      type: object
      properties:
        name:
          type: string
          description: name of roles
        id:
          type: string
          description: role identifier
        actionGroups:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              id:
                type: string
              actions:
                type: array
                items:
                  type: string
                  description: list of apis available for this role group
    roleContentCreateErrorResponse:
      title: Create Content Error Response
      allOf:
      - $ref: '#/components/schemas/roleEmptyResult'
      - $ref: '#/components/schemas/roleResponseHeader'
  securitySchemes:
    bearer:
      type: apiKey
      name: Authorization
      in: header
